### ISSUE TITLE
view2.5d:turtle-view raises NullPointerExceptation error

### ISSUE THREAD

**Issue by XXMMA** [NetLogo/View2.5D#6]
I want to show the property of turtles using 2.5d-view, but it always gives NullPointerExceptation error.
e.g. the following simple codes.

extensions [view2.5d]

turtles-own[
  energy
]

to setup
  ca
  create-turtles 50[
  set color red
  setxy random-xcor random-ycor
  set energy random 1000
  ]
  create-turtles 50[
  set energy random 1000
    setxy random-xcor random-ycor
  ]
  view2.5d:turtle-view "test" turtles [the-turtle -> [energy] of the-turtle]
  reset-ticks
end

**Comment by LaCuneta** [comment]
@XXMMA Thanks for reporting this issue, we appreciate it.  I believe what you're seeing is a known issue that was fixed after NetLogo 6.0.4 was released.

You can download a fix release of the view2.5d extension here (view2.5d_v1.1.1.zip): https://github.com/NetLogo/View2.5D/releases/tag/v1.1.1
 
You should be able to directly replace the version that comes with NetLogo 6.0.4 in the **extensions** folder to try it out.  If you get a chance to try, let me know how it works for you.

**Comment by XXMMA** [comment]
@LaCuneta I really appreciate it for your help. I was using netlogo 6.0.4 version when this problem happens. But when I replace the extension files as you said, it is fixed. I think it will be really helpful if you include an example of view2.5d:turtle-view in model library which is a powerful tool for property visualization. Thank you again for your help and your wonderful contribution to netlogo.
